language: node_js
node_js:
  - '10'
env:
  - EXTENSION_ID=lgokgkophalfnnapghjjckmeoboepfdj
script: echo "No test"
deploy:
  provider: script
  script: npm run release
  skip_cleanup: true
  on:
    branch: master
    # tags: true
